'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SteemItPostRetriever.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This software will fetch your account posts summaries
        '''and send them to the database specified. 
        '''
        '''Before using this software, you should have created 
        '''the database and ran the MySQL.SQL file script to 
        '''create the table that will store your posts summaries.
        '''
        '''To show the posts summaries on your website, edit the
        '''SteemitPosts.php changing the MySQL Information
        '''to match your MySQL Server address and credentials
        '''and upload it to your web server. You must have PHP
        '''installed on your web server for this s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EnglishDescription() As String
            Get
                Return ResourceManager.GetString("EnglishDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Este programa capturará sus posts en su cuenta y los
        '''transferirá a una base de datos especificada por usted.
        '''
        '''Antes de usar este programa, ustéd debe haber creado
        '''la base de datos y ejecutado el archivo MySQL.SQL
        '''para crear la tabla que almacenará los resumenes de
        '''sus posts.
        '''
        '''Para mostrar los posts en su página web, edite el archivo
        '''SteemitPosts.php cambiando la información de la base de
        '''datos MySQL y subiendo el archivo a su servidor web.
        '''Debe tener PHP instalado en su servidor web para que
        '''el  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SpanishDescription() As String
            Get
                Return ResourceManager.GetString("SpanishDescription", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
